# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

stages:
-stage: Build
 jobs:
 - job:BuildJob
   steps:
   - script: echo "Build completed"

-stage: Release
 dependsOn: Build
 jobs:
 -deployment: DeployJob
  environment: dev
  strategy:
   runOnce:
    deploy:
     steps:
     - script: echo "Application released successfully"
